# Jekyll configuration for Merul Badda Talks

title: "Merul Badda Talks in Maths and Physics"
email: ""
description: >- # this means to ignore newlines until ""
  Seminar series organized by the School of Data and Sciences at BRAC University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

timezone: Asia/Dhaka

collections:
  talks:
    output: true
    permalink: /talks/:path/

layouts_dir: _merulbadda/layouts
includes_dir: _merulbadda/includes

sass:
  sass_dir: _merulbadda/assets/css
  css_dir: assets/css
  style: compressed

include:
  - _merulbadda

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk

permalink: pretty
future: true


